### ISSUE TITLE
[펌웨어] 카드코딩 실행시키는 방법 변경 요청(개선사항)

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone7#16]
카드코딩 완료 후 실행시킬 때 3초 이상 누르고 손을 언제 떼야할지 잘 모르겠다는 의견이 있어서 다음과 같이 변경 요청드립니다.
- 기존 : 3초 이상 누르면 녹색 LED가 점멸되고 손을 떼면 부저음이 울리면서 작동 시작
- 변경 : 3초 이상 누르면 녹색 LED가 점멸되면서 부저음이 울리고 손을 떼면 1~2초 후 작동 시작

**Comment by realwolf** [comment]
http://dev.byrobot.co.kr/documents/kr/products/e_drive/log/updates/firmware/#heading-2019724
위의 버전을 확인해주시기 바랍니다.

**Comment by HhanGgun** [comment]
다음과 같이 정상 동작 확인하였습니다. 감사합니다.

- 변경 : 3초 이상 누르면 녹색 LED가 점멸되면서 부저음이 울리고 손을 떼면 1~2초 후 작동 시작
