### ISSUE TITLE
[펌웨어] 버튼 눌릴 때 소리 추가 요청 + 모드 진입 알림음 추가 요청

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone7#21]
카드 읽을 때나 실행할 때 뿐만 아니라 버튼이 눌릴 때마다 특정 소리가 울리게 해서 유저가 쉽게 인지할 수 있도록 요청드립니다.
소리는 카드 읽을 때, 실행할 때 울리는 소리와 다르게 하면 좋을 것 같습니다.(예: 짧은 "삐" 음)

**Comment by HhanGgun** [comment]
추가로 모드 진입 시 모드별 알림음 적용 부탁드립니다. 모드별 알림음은 다음 문서를 참조해주세요.

https://docs.google.com/spreadsheets/d/1stE-GTAyH7yph9HgjaQ7ymZkgRu0tyfYHHok-r0mNak/edit#gid=2093545189

**Comment by realwolf** [comment]
피아노 모드에서 다른 모드로 변환 시 모드 변경 소리가 두 번 울림

**Comment by realwolf** [comment]
http://dev.byrobot.co.kr/documents/kr/products/e_drive/log/updates/firmware/#heading-20191017
모드 전환 시 멜로디 알림 기능을 추가하였습니다.
그리고 정해진 동작 이외의 명령이 내려지는 경우 경고음을 울리도록 하였습니다.

**Comment by HhanGgun** [comment]
추가해주신 기능 정상 동작 확인하였습니다. 감사합니다!
