### ISSUE TITLE
[App/라인코딩] RC주행 시 후미등(브레이크등) 자동 On/Off 기능 추가 요청

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone7#22]
RC주행과 라인코딩 모드에서 후미등(브레이크등)이 주행할 때는 꺼지고 멈춰있을때는 켜지도록(자동으로) 기능 추가 요청드립니다. 
※ 현재 카드코딩과 블록코딩 모드에는 적용되어 있고, 앞으로 추가될 기능(모션주행, 핸드팔로잉 등)에도 적용 부탁드립니다.

**Comment by realwolf** [comment]
http://dev.byrobot.co.kr/documents/kr/products/e_drive/log/updates/firmware/#heading-20191023
위의 항목에서 반영하였습니다.

변경된 사항은 다음과 같습니다.
1. 브레이크등은 카드 코딩이나 수동 제어로 조작하지 못합니다.
2. 브레이크등은 모터 입력값 상태에 따라 ON/OFF로 동작합니다.
(어느 모드에나 상관없이 제어기에서 모터를 움직이기 시작하면 OFF, 모터를 정지하면 ON으로 동작합니다)

**Comment by HhanGgun** [comment]
브레이크등 자동 제어 기능 정상 동작 확인하였습니다. 감사합니다!
