### ISSUE TITLE
[펌웨어] 버튼을 길게 눌러도 카드를 인식할 수 있도록 변경 요청

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone7#24]
현재 카드를 읽을 때 버튼을 짧게 한 번 누르게 되어 있는데, 좀 더 길게 눌러도 카드를 인식할 수 있도록 변경 요청드립니다.(짧게 누르는 것을 어려워하는 사람들이 있음.)

**Comment by realwolf** [comment]
http://dev.byrobot.co.kr/documents/kr/products/e_drive/log/updates/firmware/#heading-20191018

2초 이내에 버튼을 눌렀다 뗄 경우 짧은 클릭으로 인식하게 수정하였습니다.(이전은 300ms)
3초 이상 버튼을 눌렀다 뗄 경우 긴 클릭으로 인식하게 수정하였습니다.(이전은 1.2초)
0.6초 이내에 버튼을 다시 누르는 경우 연속 입력으로 인식하게 하였습니다.(이전은 500ms)

**Comment by HhanGgun** [comment]
수정해주신것 정상 동작 확인하였습니다. 감사합니다!
