### ISSUE TITLE
[카드코딩] 전조등 밝기 약하게 변경 / 후미등 켜기 카드 제거 요청

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone7#25]
카드코딩에서 다음과 같이 기능 수정 요청드립니다.

1. 전조등 밝기를 상향등과 구별하기 쉽도록 현재보다 약하게 변경
2. 후미등 켜기 카드 제거
3. 후미등/비상등 끄기 카드 기능을 비상등 끄기만 되도록 변경

**Comment by realwolf** [comment]
http://dev.byrobot.co.kr/documents/kr/products/e_drive/log/updates/firmware/#heading-20191023
위의 업데이트에서 1, 2, 3 번 항목 모두 반영하였습니다.

**Comment by HhanGgun** [comment]
1,2,3번 수정해주신것 정상 동작 확인하였습니다. 감사합니다!
