### ISSUE TITLE
코딩카 실행 방법 통합 요청

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone7#29]
코딩카 기능 중 실행 방법이 2가지인 기능들이 유저들에게 혼란을 줄 수 있어서 1가지 방법으로 통합하려고 합니다. 다음과 같이 변경 요청드립니다.

1. 실행(카드코딩, 라인코딩, 모션코딩, 따라가기 모드 공통)
- 기존: 2번 연속 push / 3초 이상 push
- 변경: 2번 연속 push

2. 리셋(bias)
- 기존: 5번 연속 push / 10초 이상 push
- 변경: 5번 연속 push

3. 피아노 모드 실행
- 기존: 멜로디 실행 카드 읽기 / 3초 이상 push
- 변경: 멜로디 실행 카드 읽기
※ 피아노 모드는 push할 때마다 음이 연주되어야 하기 때문에 연속 push 입력이 안되기 때문에 실행 카드 별도 제공

4. '코딩 끝' 카드
- 기존: '코딩 끝' 카드 읽지 않아도 실행 가능
- 변경: '코딩 끝' 카드 무조건 읽어야 실행 가능

**Comment by realwolf** [comment]
http://dev.byrobot.co.kr/documents/kr/products/e_drive/log/updates/firmware/#heading-2019118
위의 업데이트에서 수정 완료하였습니다.

**Comment by HhanGgun** [comment]
변경해주신 기능 정상 동작 확인하였습니다. 감사합니다!
