### ISSUE TITLE
[펌웨어] 멜로디 무한반복 시 재생되다가 멈추는 오류 발생(카드/블록)

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone7#3]
멜로디1~멜로디8 명령을 무한반복과 같이 사용하면 멜로디가 재생되다가 멈추고, 이 후 코딩카의 buzzer에서 소리가 재생되지 않습니다.

- 카드코딩과 블록코딩에서 동일하게 발생함
- 카드 입력 순서 : 카드코딩 시작 → 무한반복 → 멜로디1 → 반복 끝
- 블록 입력 순서 : 시작 → 무한반복 → (무한반복)멜로디1

**Comment by realwolf** [comment]
http://dev.byrobot.co.kr/documents/kr/products/e_drive/log/updates/firmware/#heading-2019724
위의 버전을 확인해주시기 바랍니다.

**Comment by HhanGgun** [comment]
메모리 버퍼 사이즈 제한으로 멜로디3 or 4(멜로디 중에서 가장 긴 멜로디)를 10번 반복시 8번만 반복되는 문제가 발생합니다.
멜로디 3 or 4가 최대 10번까지 반복할 수 있도록 버퍼 사이즈 변경 부탁드립니다. (단, 여러 개의 멜로디를 반복 재생할 경우 버퍼 사이즈를 초과하는 것은 무시)

**Comment by realwolf** [comment]
http://dev.byrobot.co.kr/documents/kr/products/e_drive/log/updates/firmware/#heading-2019725
위의 버전을 확인해주시기 바랍니다.

**Comment by HhanGgun** [comment]
정상 동작 확인하였습니다. 감사합니다.
