### ISSUE TITLE
카드코딩과 라인코딩 모드에서 색상 인식 로직 분리 요청

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone7#30]
현재 통합되어 있는 색상 인식 로직을 카드코딩과 라인코딩 모드에서 각각 독립적으로 동작하도록 분리 작업 요청드립니다.
(사유: 샘플 카드에서 saturation 값이 낮게 나오는 컬러들이 있음)

**Comment by realwolf** [comment]
http://dev.byrobot.co.kr/documents/kr/products/e_drive/log/updates/firmware/#heading-20191113
위의 업데이트를 확인해주시기 바랍니다.

**Comment by HhanGgun** [comment]
수정해주신것 정상 동작 확인하였습니다. 감사합니다!
