### ISSUE TITLE
[펌웨어] 비상등 동작 수정 요청(카드)

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone7#4]
카드코딩에서는 비상등이 후미등 LED가 깜빡이는데, 후미등이 아닌 좌/우 깜빡이 LED가 깜빡이는 것으로 수정 요청드립니다. (블록코딩과 동일하게 동작하는 것으로 변경. 블록코딩에서는 비상등이 좌/우 깜빡이 LED가 깜빡임)

- 카드 입력 순서 : 카드코딩 시작 → 비상등 켜기 → 일시정지 → 일시정지 → 일시정지 → 후미등/비상등 끄기 → 카드코딩 끝

**Comment by realwolf** [comment]
http://dev.byrobot.co.kr/documents/kr/products/e_drive/log/updates/firmware/#heading-2019724
위의 버전을 확인해주시기 바랍니다.

**Comment by HhanGgun** [comment]
비상등 실행시 좌/우 깜빡이 LED가 깜빡이는 것으로 변경된건 확인했는데, 비상등 끄기 명령을 사용하면 비상등이 꺼지지 않습니다.

**Comment by realwolf** [comment]
http://dev.byrobot.co.kr/documents/kr/products/e_drive/log/updates/firmware/#heading-2019725
위의 버전을 확인해주시기 바랍니다.

**Comment by HhanGgun** [comment]
비상등 끄기와 비상등 켜기 단독 사용시 LED 점등 정상 동작 확인하였습니다. 감사합니다.
