### ISSUE TITLE
[펌웨어] 조건 카드에서 '조건이 맞지 않으면' 사용 시 중간에 실행이 중단되는 오류 발생(카드)

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone7#5]
카드코딩에서 조건 카드 중 '조건이 맞지 않으면' 카드와 무한반복을 함께 사용하면 중간에 실행이 중단되는 오류가 발생합니다.

- 블록코딩에서는 정상 동작함
- 카드 입력 순서 : '카드코딩 시작' → '무한 반복' → '앞쪽 장애물 발견하면,' → 'U턴' → '조건이 맞지 않으면,' → '1칸 전진' → '조건 끝' → '반복 끝' → '카드코딩 끝'
(위와 같이 카드코딩해서 실행하면 2번째 장애물 발견해서 U턴할 때 종료됩니다.)

**Comment by realwolf** [comment]
http://dev.byrobot.co.kr/documents/kr/products/e_drive/log/updates/firmware/#heading-2019725
위의 버전을 확인해주시기 바랍니다.

**Comment by HhanGgun** [comment]
정상 동작 확인하였습니다. 감사합니다!
